name: 引导构建

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: DS3622xs+
            version: 7.1.0-42661

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3
      
      - name: 环境准备
        run: |
          sudo apt update
          sudo apt-get install -y curl bspatch jq git
          git clone https://github.com/Online24Hours/redpill-load.git /home/runner/redpill-load
          cd /home/runner/redpill-load 
          ./ext-manager.sh add 'https://github.com/jumkey/redpill-load/raw/develop/redpill-misc/rpext-index.json'
          ./ext-manager.sh add 'https://github.com/pocopico/redpill-load/raw/develop/redpill-acpid/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/tg3/rpext-index.json'
          ./ext-manager.sh add 'https://github.com/pocopico/redpill-load/raw/develop/redpill-virtio/rpext-index.json'
          
          wget https://raw.githubusercontent.com/Online24Hours/Redpill_Build/main/PAT.sh -O /home/runner/redpill-load/PAT.sh
          chmod +x PAT.sh
          ./PAT.sh

          cd /home/runner/redpill-load
          BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=user_config.json ./build-loader.sh 'DS3622xs+' '7.1.0-42661'
          
      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v3
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: /home/redpill-load/images/*
          if-no-files-found: error
