name: 引导构建

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: DS3622xs+
            version: 7.1.0-42661

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3
      
      - name: 环境准备
        run: |
          sudo apt update
          sudo apt-get install -y curl bspatch jq git
          git clone https://github.com/Online24Hours/redpill-load.git /home/runner/redpill-load
          cd /home/runner/redpill-load 
          ./ext-manager.sh add 'https://github.com/jumkey/redpill-load/raw/develop/redpill-misc/rpext-index.json'
          ./ext-manager.sh add 'https://github.com/pocopico/redpill-load/raw/develop/redpill-acpid/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/tg3/rpext-index.json'
          ./ext-manager.sh add 'https://github.com/pocopico/redpill-load/raw/develop/redpill-virtio/rpext-index.json'

          cd /home/runner/redpill-load/cache
          curl -L https://cndl.synology.cn/download/DSM/release/7.1/42661-1/DSM_DS3622xs+_42661.pat -o ds.pat
          mkdir synoesp
          curl --location https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_DS3622xs+_42218.pat --output oldpat.tar.gz
          tar -C./synoesp/ -xf oldpat.tar.gz rd.gz
          cd synoesp
          xz -dc < rd.gz >rd 2>/dev/null || echo "extract rd.gz"
          echo "finish"
          cpio -idm <rd 2>&1 || echo "extract rd"
          mkdir extract && cd extract
          cp ../usr/lib/libcurl.so.4 ../usr/lib/libmbedcrypto.so.5 ../usr/lib/libmbedtls.so.13 ../usr/lib/libmbedx509.so.1 ../usr/lib/libmsgpackc.so.2 ../usr/lib/libsodium.so ../usr/lib/libsynocodesign-ng-virtual-junior-wins.so.7 ../usr/syno/bin/scemd ./
          ln -s scemd syno_extract_system_patch
          cd ../..
          mkdir pat
          #tar xf ds.pat -C pat
          ls -lh ./
          sudo LD_LIBRARY_PATH=synoesp/extract synoesp/extract/syno_extract_system_patch ds.pat pat || echo "extract latest pat"
          cd pat
          tar -czvf archive.tar.gz ./
          mv archive.tar.gz ../ds3622xsp_42661.pat
          cd ../
          rm -r ds.pat oldpat.tar.gz pat synoesp
          sha256sum ds3622xsp_42661.pat

          cd /home/runner/redpill-load
          BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=user_config.json ./build-loader.sh 'DS3622xs+' '7.1.0-42661'
          
      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v3
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: /home/redpill-load/images/*
          if-no-files-found: error
