name: Build RS4021xs+

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: RS4021xs+
            version: 7.0.1-42218

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3
        
      - name: 获取当前时间
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
        
      - name: 环境准备
        run: |
          sudo apt update
          sudo apt-get install -y curl bspatch jq git
          git clone https://github.com/dogodefi/redpill-load.git /home/runner/redpill-load
          wget https://raw.githubusercontent.com/Online24Hours/Redpill_Build/main/rs4021xsp_user_config.json -O /home/runner/redpill-load/rs4021xsp_user_config.json
          wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill/releases/redpill-4.4.180plus-broadwellnk.tgz
          tar zxvf redpill-4.4.180plus-broadwellnk.tgz -C ./
          mv ./redpill.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.180+.ko
          
      - name: 修改PAT校验值
        run: |
          sed -i s/a72076b1a5c148e775e9542916e2f07fe18d8676dc7396ed69355a9a0a38b36c/7afca3970ac7324d7431c1484d4249939bedd4c18ac34187f894c43119edf3a1/g '/home/runner/redpill-load/${{matrix.platform}}/${{matrix.version}}/config.json'
          
      - name: 编译引导
        run: |
          cd /home/runner/redpill-load
          sudo BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=rs4021xsp_user_config.json ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
          
      - name: 上传引导镜像到 Github Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Synoboot
          name: Synoboot Build ${{steps.date.outputs.today}}
          body: DSM ${{matrix.version}}
          draft: false
          prerelease: false
          files: |
            /home/runner/redpill-load/images/*.img
          
      - name: 上传引导镜像到 Github Actions
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.platform}} ${{matrix.version}}
          path: /home/runner/redpill-load/images/*.img
          if-no-files-found: error
