name: 删除所有 Release 项目

on:
  schedule:
    - cron: '30 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Delete Older Releases
    
    steps:
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: Online24Hours/Redpill_Build
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
