name: 解密PAT

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    name: dsm-${{matrix.platform}}-${{matrix.version}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: DS3622xs+
            version: 7.1.0-42661

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3
        
      - name: 获取当前时间
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      
      - name: 解密PAT文件
        run: |
          mkdir -p /home/runner/PAT/
          cd /home/runner/PAT
          wget https://raw.githubusercontent.com/Online24Hours/Redpill_Build/main/${{matrix.platform}}-${{matrix.version}}.sh -O PAT.sh
          chmod +x PAT.sh
          ./PAT.sh
          
      - name: 上传解密 PAT 到 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: UNPACK
          name: PAT_Patch ${{steps.date.outputs.today}}
          body: PAT_Patch ${{matrix.platform}} ${{matrix.version}}
          draft: false
          prerelease: false
          files: |
            /home/runner/PAT/*.pat

      - name: 上传解密 PAT 到 Github Actions
        uses: actions/upload-artifact@v3
        with:
          name: PAT_Patch
          path: /home/runner/PAT/*.pat
          if-no-files-found: error
